-- Generated by nwg-displays on 2026-09-27 at 12:36:01. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@59.95",
    position = "1920x0",
    scale = 1.0,
    vrr = 0,
    transform = 1
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@144.01",
    position = "0x1000",
    scale = 1.0,
    vrr = 0
})
