# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000105)
$foreground = rgb(DEE0E3)
$color0 = rgb(000105)
$color1 = rgb(202C36)
$color2 = rgb(26313B)
$color3 = rgb(525A61)
$color4 = rgb(4F5E6C)
$color5 = rgb(726252)
$color6 = rgb(7A7D82)
$color7 = rgb(C8CBCE)
$color8 = rgb(8C8E90)
$color9 = rgb(2B3B48)
$color10 = rgb(32424E)
$color11 = rgb(6E7881)
$color12 = rgb(6A7D90)
$color13 = rgb(98836E)
$color14 = rgb(A2A7AE)
$color15 = rgb(C8CBCE)
